### PR TITLE
Changed the order in which new viewers are added to the workspace

### LINKED ISSUE #25: As a user, I want to open documents selected from the TOC in the viewer to the right
Having documents selected from the TOC load in the viewer to the right, not the left of frames currently open. The current scheme loads new docs to the left of current frames in the viewer, which means users have to think in reverse if they are opening up a set of files to work with, and have a specific order they wish them to display in.

### LINKED ISSUE #39: Remove “Clean Up Project” button from TOC window
Can we remove the “Clean Up Project” button from the TOC window - I believe it serves no purpose now?

### PR DESCRIPTION
**Pull request by jamiefolsom**
### What does this do?

1. Makes it so that newly opened windows appear to the right of existing ones, rather than to the left. Closes #25 
1. Removes Clean up project button from project viewer. Closes #39 
1. Also, replaces an incorrectly encoded jquery plugin file that prevented build. (jquery.event.drag-2.2.js). No related issue.

### How to test

1. Go to http://dm.performantsoftware.com
1. Log in
1. Open a project
1. Note that there is no longer a "Clean Up Project" button next to the "Done" button at bottom right of the project viewer dialog (re: issue #39)
1. Select a file to open from the list
1. Close the project viewer. 
1. Note location of the file.
1. Open the project again
1. Select another file to open from the list
1. Close the project viewer. 
1. Note second file opened to the right (re: issue #25)
1. Lather, rinse, repeat.

### CODE REVIEW

**Comment by jamiefolsom** [comment]
@gremid Following up on my question to you via email, here's the related PR.

**Comment by jamiefolsom** [comment]
Hi @SteveMarvin -- this is ready for testing on staging. Let me know if you have questions. Thanks!

**Comment by SteveMarvin** [comment]
It works like a charm. 👍

**Comment by jamiefolsom** [comment]
Cool, thanks, @SteveMarvin!

**Pull request merged**
