### PR TITLE
Make frames reorderable in viewer grid through dragging

### LINKED ISSUE #23: As a user, I want to drag frames to different spots in the workspace

### PR DESCRIPTION
**Pull request by akstuhl**
### What does this PR do?
Adds google closure library DragListGroup functionality to the viewer grid so that viewer containers can be reordered on the fly.

### What issues does it address?
Closes #23 

### How to test
On the [staging site](http://67.207.158.85/), add a varying number of frames to the workspace and try reordering them by clicking and dragging on any space in their title areas that isn't occupied by text or an icon. Switch layouts and add new frames following a rearrangement to confirm content appears correctly.

### CODE REVIEW

**Review by jamiefolsom — APPROVED** [review]
👍 Looks good, merge at will!

**Comment by jamiefolsom** [comment]
@SteveMarvin I would welcome your taking a look at this once it's merged and deployed to staging. If you find issues at that point, it would make sense to create new tickets and put them in New Issues, assigned to @akstuhl. Thx!

**Comment by akstuhl** [comment]
Hi @SteveMarvin, this one has also just been pushed to staging (http://67.207.158.85/) and is ready for testing.

**Comment by SteveMarvin** [comment]
Unless I am misunderstanding, this is not working for me. If I click on the title bar, it opens the title for renaming. If I click and drag, I highlight portions of the frame. If I change the Lock status, that still doesn't work. Am I misunderstanding what I am going for here?

**Pull request merged**
